@postId = 6738b6d647545097428cbbe9
@commentId = 6738b9c30e8d99f8abfb5db3
@sender = 123

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~ Posts ~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Add a new post
POST http://localhost:3001/post
Content-Type: application/json

{
  "title": "My new Post",
  "content": "This is the content of my first post!",
  "senderId": "{{sender}}"
}

###

# Get all posts
GET http://localhost:3001/post

###

# Get a post by ID
GET http://localhost:3001/post/{{postId}}

###

# Get posts by sender
GET http://localhost:3001/post?sender={{sender}}

###

# Update a post
PUT http://localhost:3001/post/{{postId}}
Content-Type: application/json

{
  "title": "My new Post - Updated",
  "content": "Updated content of my post!"
}

###

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~ Comments ~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

# Create a new comment
POST http://localhost:3001/comment
Content-Type: application/json

{
  "postId": "{{postId}}",
  "content": "This is my comment on the post!",
  "author": "John Doe"
}

###

# Get all comments
GET http://localhost:3001/comment

###

# Get a comment by ID
GET http://localhost:3001/comment/{{commentId}}

###

# Get all comments for a specific post
GET http://localhost:3001/comment/post/{{postId}}

###

# Update a comment
PUT http://localhost:3001/comment/{{commentId}}
Content-Type: application/json

{
  "content": "This is my updated comment!",
  "author": "John Doe"
}

###

# Delete a comment
DELETE http://localhost:3001/comment/{{commentId}}