@postId = 6976033a5f8b160c398f1db1
@commentId = 6976828b4b02780898b80808
@sender = 123

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~~ Posts ~~~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

###create new post
POST http://localhost:3001/post
Content-Type: application/json

{
    "title": "post about food",
    "content": "This is a post about pasta.",
    "senderId": 315005
}

###get all posts
GET http://localhost:3001/post

###get post by id
GET http://localhost:3001/post/697603825f8b160c398f1db3

###get posts by sender Id
GET http://localhost:3001/post?sender=315005
###update post 
PUT http://localhost:3001/post/6976033a5f8b160c398f1db1
Content-Type: application/json

{
    "title": "updated post about new fashion",
    "content": "This is an updated post about pants.",
    "senderId": 7171
}

#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#
#~~~~~~~~~~ Comments ~~~~~~~~~~#
#~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~#

###Create a new comment
POST http://localhost:3001/comment
Content-Type: application/json

{
  "postId": "{{postId}}",
  "content": "This is my comment on the post!",
  "author": "John Doe"
}

### Get all comments
GET http://localhost:3001/comment

###Get a comment by ID
GET http://localhost:3001/comment/{{commentId}}

###Get all comments for a specific post
GET http://localhost:3001/comment/post/{{postId}}

### Update a comment
PUT http://localhost:3001/comment/{{commentId}}
Content-Type: application/json

{
  "content": "This is my updated comment!",
  "author": "John Doe"
}
### Delete a comment
DELETE http://localhost:3001/comment/{{commentId}}