###create new post
POST http://localhost:3000/post
Content-Type: application/json

{
    "title": "post about food",
    "content": "This is a post about pasta.",
    "senderId": 315005
}

###get all posts
GET http://localhost:3000/post

###get post by id
GET http://localhost:3000/post/697603825f8b160c398f1db3

###get posts by sender Id
GET http://localhost:3000/post?sender=315005